<a href="https://colab.research.google.com/github/atmakurirevathi77/bridge-load-/blob/main/MMH_A2_LRYFN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
PROJECT OBJECTIVE
-----------------
Three supports carry a bridge.

Loads act at three points on the bridge.
We represent the simplified structural model as:

                    A X = B

where:
    A = 3x3 bridge/support coefficient matrix
    X = unknown reaction-force vector
    B = load vector

The system is solved using:
    1. Matrix inverse
    2. Direct linear solver

Then one load is changed to simulate a truck moving,
and the new support reactions are calculated.

IMPORTANT:
This is an educational mathematical model, NOT a replacement
for professional structural-engineering software.
"""

'\nPROJECT OBJECTIVE\n-----------------\nThree supports carry a bridge.\n\nLoads act at three points on the bridge.\nWe represent the simplified structural model as:\n\n                    A X = B\n\nwhere:\n    A = 3x3 bridge/support coefficient matrix\n    X = unknown reaction-force vector\n    B = load vector\n\nThe system is solved using:\n    1. Matrix inverse\n    2. Direct linear solver\n\nThen one load is changed to simulate a truck moving,\nand the new support reactions are calculated.\n\nIMPORTANT:\nThis is an educational mathematical model, NOT a replacement\nfor professional structural-engineering software.\n'

In [ ]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

from IPython.display import display, Markdown

# Make NumPy output easier to read
np.set_printoptions(precision=3, suppress=True)

print("Libraries imported successfully.")

Libraries imported successfully.


In [ ]:
A = np.array([
    [4.0, 1.0, 0.5],
    [1.0, 5.0, 1.0],
    [0.5, 1.0, 4.0]
], dtype=float)


# ------------------------------------------------------------
# Original loads at three points
# ------------------------------------------------------------

loads_before = np.array([
    100.0,   # Load at Point 1 (kN)
    150.0,   # Load at Point 2 (kN)
    80.0     # Load at Point 3 (kN)
], dtype=float)


# ------------------------------------------------------------
# Truck movement:
# Change the load at Point 2
# ------------------------------------------------------------

loads_after = np.array([
    100.0,   # Point 1 remains unchanged
    220.0,   # Truck moves here / load increases
    80.0     # Point 3 remains unchanged
], dtype=float)


print("Bridge model configured.")
print("\nMatrix A:")
print(A)

print("\nLoads before truck movement:")
print(loads_before)

print("\nLoads after truck movement:")
print(loads_after)

Bridge model configured.

Matrix A:
[[4.  1.  0.5]
 [1.  5.  1. ]
 [0.5 1.  4. ]]

Loads before truck movement:
[100. 150.  80.]

Loads after truck movement:
[100. 220.  80.]


In [ ]:
def validate_inputs(A, loads):
    """Check whether the mathematical inputs are valid."""

    A = np.asarray(A, dtype=float)
    loads = np.asarray(loads, dtype=float)

    # Check matrix dimensions
    if A.shape != (3, 3):
        raise ValueError("Matrix A must be 3 x 3.")

    # Check load vector
    if loads.shape != (3,):
        raise ValueError("Load vector must contain exactly 3 values.")

    # Check numerical values
    if not np.all(np.isfinite(A)):
        raise ValueError("Matrix A contains invalid values.")

    if not np.all(np.isfinite(loads)):
        raise ValueError("Loads contain invalid values.")

    # Check determinant
    determinant = np.linalg.det(A)

    if abs(determinant) < 1e-10:
        raise ValueError(
            "Matrix A is singular or nearly singular. "
            "A unique solution cannot be guaranteed."
        )

    return True


validate_inputs(A, loads_before)
validate_inputs(A, loads_after)

print("✓ Inputs are valid.")
print(f"✓ det(A) = {np.linalg.det(A):.4f}")
print("✓ A unique solution exists.")

✓ Inputs are valid.
✓ det(A) = 71.7500
✓ A unique solution exists.


In [ ]:
print("=" * 60)
print("MATHEMATICAL MODEL")
print("=" * 60)

print("\nWe use the linear system:")
print("        A X = B")

print("\nA =")
print(A)

print("\nX =")
print("[R1]")
print("[R2]")
print("[R3]")

print("\nB =")
print(loads_before)

print("\nTherefore:")
print("A × [R1, R2, R3]^T = B")

print("\nWhere:")
print("R1 = reaction at Support 1")
print("R2 = reaction at Support 2")
print("R3 = reaction at Support 3")

MATHEMATICAL MODEL

We use the linear system:
        A X = B

A =
[[4.  1.  0.5]
 [1.  5.  1. ]
 [0.5 1.  4. ]]

X =
[R1]
[R2]
[R3]

B =
[100. 150.  80.]

Therefore:
A × [R1, R2, R3]^T = B

Where:
R1 = reaction at Support 1
R2 = reaction at Support 2
R3 = reaction at Support 3


In [ ]:
A_sym = sp.Matrix(A)

det_A = A_sym.det()
A_inverse = A_sym.inv()

print("Determinant of A:")
print(det_A)

print("\nMatrix inverse A⁻¹:")
display(A_inverse)

Determinant of A:
71.7500000000000

Matrix inverse A⁻¹:


Matrix([
[  0.264808362369338, -0.048780487804878, -0.0209059233449477],
[ -0.048780487804878,  0.219512195121951,  -0.048780487804878],
[-0.0209059233449477, -0.048780487804878,   0.264808362369338]])

In [ ]:
A_inv_numpy = np.linalg.inv(A)

reactions_before = A_inv_numpy @ loads_before

print("=" * 60)
print("ORIGINAL LOAD CASE")
print("=" * 60)

print("\nFormula:")
print("X = A⁻¹B")

print("\nReaction forces:")

for i, reaction in enumerate(reactions_before, start=1):
    print(f"Support {i}: {reaction:.3f} kN")

ORIGINAL LOAD CASE

Formula:
X = A⁻¹B

Reaction forces:
Support 1: 17.491 kN
Support 2: 24.146 kN
Support 3: 11.777 kN


In [ ]:

print("Reaction forces using np.linalg.solve():")
print(reactions_before_solver)

print("\nReaction forces using matrix inverse:")
print(reactions_before)

difference = np.max(
    np.abs(reactions_before - reactions_before_solver)
)

print(f"\nMaximum difference: {difference:.10f}")

if difference < 1e-9:
    print("✓ Both methods agree.")
else:
    print("⚠ Check the numerical calculation.")

Reaction forces using np.linalg.solve():


NameError: name 'reactions_before_solver' is not defined